<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24794" started-at="2017-11-12T18:07:54Z" finished-at="2017-11-12T18:08:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24794" started-at="2017-11-12T18:07:54Z" finished-at="2017-11-12T18:08:19Z">
      <class name="local_Tests.Local_Tests">
        <test-method status="PASS" signature="Setup()[pri:0, instance:local_Tests.Local_Tests@18eed359]" name="Setup" is-config="true" duration-ms="23161" started-at="2017-11-12T21:07:54Z" finished-at="2017-11-12T21:08:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="FAIL" signature="addition(java.lang.String, java.lang.String)[pri:0, instance:local_Tests.Local_Tests@18eed359]" name="addition" duration-ms="897" started-at="2017-11-12T21:08:17Z" data-provider="numbers" finished-at="2017-11-12T21:08:18Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: addition([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(com.codoid.products.fillo.Field)com.codoid.products.fillo.Field@5bfa8cc5,(com.codoid.products.fillo.Field)com.codoid.products.fillo.Field@666b83a4]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: addition([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(com.codoid.products.fillo.Field)com.codoid.products.fillo.Field@5bfa8cc5,(com.codoid.products.fillo.Field)com.codoid.products.fillo.Field@666b83a4]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:49)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1187)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addition -->
        <test-method status="PASS" signature="End()[pri:0, instance:local_Tests.Local_Tests@18eed359]" name="End" is-config="true" duration-ms="695" started-at="2017-11-12T21:08:18Z" finished-at="2017-11-12T21:08:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- End -->
      </class> <!-- local_Tests.Local_Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
